apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-data
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteMany

  storageClassName: ""

  volumeName: nginx-nfs-pv

  resources:
    requests:
      storage: 1Gi
