apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: prepare-nfs-directory
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c

          args:
            - |
              echo "Preparing NFS directory..."
              mkdir -p /nfs/nginx-html
              if [ ! -f /nfs/nginx-html/index.html ]; then
                cat > /nfs/nginx-html/index.html <<'HTML'
              <!DOCTYPE html>
              <html>
              <head>
                  <title>Nginx Kubernetes NFS Demo</title>
                  <style>
                      body {
                          font-family: Arial, sans-serif;
                          background: #f5f5f5;
                          text-align: center;
                          padding-top: 100px;
                      }
                      .container {
                          background: white;
                          width: 600px;
                          margin: auto;
                          padding: 40px;
                          border-radius: 10px;
                          box-shadow: 0 0 15px #ccc;
                      }
                      h1 {
                          color: #009639;
                      }
                  </style>
              </head>

              <body>
              <div class="container">
              <h1>Nginx Running on Kubernetes</h1>
              <p>
              This page is stored on an NFS Persistent Volume.
              </p>
              <p>
              NFS storage is shared between multiple Nginx pods.
              </p>
              <p>
              Managed using Kubernetes and Argo CD.
              </p>
              </div>
              </body>
              </html>
              HTML
              fi
              echo "NFS directory prepared successfully."

          volumeMounts:
            - name: nginx-storage
              mountPath: /nfs

      containers:
        - name: nginx
          image: nginx:1.29-alpine
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          volumeMounts:
            - name: nginx-storage
              mountPath: /usr/share/nginx/html
              subPath: nginx-html


          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi


          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

      volumes:
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-data
